version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  dotnetapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnetapp
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=tasks_todo;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "5000:80"
